### ISSUE TITLE
`#![no_std]` Support

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/mirror-mirror#14]
I was scrolling through the org github and just happened to see this. 😄 I was interested in trying it out in one of my project, and I was wondering if you'd consider adding `#![no_std]` support? As far as I can tell nearly all of the crate is implemented with types in `core` and `alloc`, having it available without std would allow this to be used by a lot more lower level libraries such as codec/serialisation frameworks.

**Comment by davidpdrsn** [comment]
Sure! I've never actually done a `non_std` crate before so would be cool to try.

Is there more to it than using the types from `core` and `alloc`?

**Comment by XAMPPRocky** [comment]
> Is there more to it than using the types from core and alloc?

For libraries nope, all you do is use those types set `#![no_std]` and that's it. For applications it's more complicated as you need to specify your main/start function.

If you want to add `std` support for select types, you should typically have the crate be `#[no_std]` by default, and provide a `std` feature (rather than opposite, having it default to `std` and then enabling a `no_std` feature.), as that makes `default-features = false` behave intuitively.
