### ISSUE TITLE
Does `debug()` need to be a method in the `Reflect` trait?

### ISSUE THREAD

**Issue by bnjbvr** [EmbarkStudios/mirror-mirror#73]
I'm looking at the code right now and I'm wondering why there's a separate notion of debug formatting for `Reflect`ables values? What are the benefits compared to letting the type implementing `Reflect` implement `Debug` if they want to?

**Comment by davidpdrsn** [comment]
It's so we can implement `Debug` for `dyn Reflect` (https://github.com/EmbarkStudios/mirror-mirror/blob/main/crates/mirror-mirror/src/lib.rs#L577).

We could technically use https://github.com/EmbarkStudios/mirror-mirror/blob/main/crates/mirror-mirror/src/lib.rs#L1283 but using the `Debug` impl directly from the type will give more precise output, specially if the reflection type uses `ReflectRef::Opaque`. It might also be slightly faster.

**Comment by bnjbvr** [comment]
Ok, so `Reflect` types don't have to provide a `Debug` implementation, but we can still _get_ a free `Debug`-like implementation for those types, based on the reflected fields (and in theory, we could add metadata in there, if we wanted to).
